config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'} 
   
   resources :users 
   root 'users#index'
    
  resources :tweets 
  root 'tweets#index'
	
  resources :relationships, :only => [:create, :destroy]

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :active_relationships, class_name:"Relationship",  foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followers, through: :passive_relationships, source: :follower
  has_many :following, through: :active_relationships, source: :followed


  def follow(user)
  	active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
  	active_relationships.find_by(followed_id: user.id).destroy
  end


 def following?(user)
 	following.include?(user)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end
end
	

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :identify_user


  def create
    current_user.follow(@user)
    redirect_to tweets_path
  end

  def destroy
    current_user.unfollow(@user)
    redirect_to tweets_path
  end

 private
  def identify_user
   @user = User.find_by(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]
	
	
    
    def index
	  @tweets = Tweet.all
	end

	def new
	  @tweet = current_user.tweets.build
	end

	def create
	  @tweet = current_user.tweets.build(tweet_params)
	    if @tweet.save
			# 'Tweet was successfully saved' and I18n
		  flash[:success] = 'Tweet was successfully saved'
		  redirect_to tweet_path(@tweet)
		else
		  render :new
		end
	end

	def edit
	  @tweet = Tweet.find(params[:id])
	end

	def show
	  @tweet = Tweet.find(params[:id])
	end

	def update
	  @tweet = Tweet.find(params[:id])
	    if @tweet.update(tweet_params)
	      flash[:success] = 'Tweet was successfully updated'
		  redirect_to tweet_path(@tweet)
		else
		  render :edit
		end
	end

	def destroy
		@tweet = Tweet.find(params[:id])
		@tweet.destroy
	end

	private

	def tweet_params
	  params.require(:tweet).permit(:content)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="control">
      <%= link_to 'New Tweet', new_tweet_path, class: "button is-info is-inverted"%>
    </p>
   <p>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "button is-info is-inverted"%>
    </p>
    <%= yield %>
  </body>
</html>

app/views/relationships/new.html.erb
<h1> New Relationships</h1>
<%= form_for @relationship do |f| %>
<p>
  <%= f.label :follower_id %> <br>
  <%= f.text_field :follower_id %>
</p>
<p>
  <%= f.label :followed_id %> <br>
  <%= f.text_field :followed_id %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/_count.html.erb
<p>
  <th>Tweets</th>
  <th><%= current_user.tweets.count %></th>
<p>
<p>
  <th>Followers</th>
  <th><%= current_user.followers.count %></th>
</p>
<p>
  <th>Following</th>
  <th><%= current_user.following.count %></th>
</p>

app/views/tweets/_user_details.html.erb
<h1>User Details</h1>
<p>
	Name: <%= current_user.name %>
</p>
<p>
	Username: <%= current_user.username %>
</p>

app/views/tweets/edit.html.erb
<h1> Edit Tweet</h1>
<%= form_for @tweet do |f| %>
<p>
  <%= f.label :tweet %> <br>
  <%= f.text_area :content %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1> Twitter</h1>
<% if user_signed_in? %>
<%= render 'count' %>
<%= render 'user_details' %>
<% end %>
<table>
  <% @tweets.each do |tweet| %>
  <tr>
    <% if user_signed_in? && current_user.id == tweet.user_id %>
      <td><%= tweet.content %></td>
      <td><%= link_to 'Show', tweet_path(tweet) %></td>
     <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
     <td><%= link_to 'Destroy', tweet_path(tweet),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>
<table>
  <th>List of Tweets</th>
  <% @tweets.each do |tweet| %>
    <tr>
      <td><%= tweet.content %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Users', users_path %>




  
 

app/views/tweets/new.html.erb
<h1> New Tweet</h1>
<%= form_for @tweet do |f| %>
<p>
  <%= f.label :tweet %> <br>
  <%= f.text_area :content %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p>
Tweet: <%= @tweet.content %>
</p>
<%= link_to 'Back', tweets_path %>
<%= link_to 'Edit', edit_tweet_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<% @users.each do |user| %>
<p>
<%= user.name %>
</p>
<p>
<%= user.username %><br/>
</p>
<%= link_to "unFollow", relationship_path(:id => user.id), :method => :delete, :remote => 'true', :class => "FollowButton_small"%>
<%= link_to 'follow', relationships_path(:id => user.id), :method => :post, :remote => 'true', :class => "FollowButton_small"%>
<% end %>